"""
ReportGenerator -- Generates final vulnerability reports.

Produces two formats:
1. JSON: Machine-readable, complete structured data
2. Markdown: Human-readable, suitable for submission/display
"""

import json
from pathlib import Path
from typing import Union

from loguru import logger

from ..verifier.models import FinalReport, Phase4Statistics, ReportMetadata, VulnerabilityEntry


class ReportGenerator:
    """Generates the final vulnerability report in JSON and Markdown."""

    def generate(self, report: FinalReport) -> FinalReport:
        return report

    # -- JSON Output ---------------------------------------------------------

    def to_json(self, report: FinalReport, path: Union[str, Path]) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        data = report.to_dict()
        path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        logger.info(f"JSON report saved to {path}")

    # -- Markdown Output -----------------------------------------------------

    def to_markdown(self, report: FinalReport, path: Union[str, Path]) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        md = self._build_markdown(report)
        path.write_text(md, encoding="utf-8")
        logger.info(f"Markdown report saved to {path}")

    def _build_markdown(self, report: FinalReport) -> str:
        lines = [
            "# Firmware Vulnerability Analysis Report",
            "",
            f"**Firmware:** `{report.metadata.firmware_name}`",
            f"**Analysis Date:** {report.metadata.analysis_date or 'N/A'}",
            f"**Firmware Hash:** `{report.metadata.firmware_hash or 'N/A'}`",
            "",
            "---",
            "",
        ]
        lines.extend(self._build_executive_summary(report))
        lines.extend(["", "---", ""])
        lines.extend(self._build_statistics_section(report.statistics))
        lines.extend(["", "---", ""])

        if report.vulnerabilities:
            lines.append(f"## Vulnerability Details ({report.count} found)")
            lines.append("")
            for i, vuln in enumerate(report.vulnerabilities, 1):
                lines.extend(self._build_vulnerability_section(i, vuln))
                lines.extend(["", "---", ""])
        else:
            lines.append("## Vulnerability Details")
            lines.append("")
            lines.append("No vulnerabilities were confirmed in this analysis.")
            lines.append("")

        lines.extend([
            "## Methodology",
            "",
            "This report was generated by FuzzingBrain's firmware vulnerability discovery pipeline:",
            "",
            "1. **Phase 1 -- Static Analysis:** Ghidra decompilation + binwalk extraction",
            "2. **Phase 2 -- Attack Surface Identification:** LLM-based semantic analysis",
            "3. **Phase 3 -- Multi-Agent Cross-Examination:** 3 specialized analysts with cross-review",
            "4. **Phase 4 -- Dynamic Verification:** FirmAE (L1) -> QEMU (L2) -> Static Assessment (L3)",
            "",
        ])
        return "\n".join(lines)

    def _build_executive_summary(self, report: FinalReport) -> list:
        stats = report.statistics
        lines = ["## Executive Summary", ""]
        lines.append(f"- **P0 SPs analyzed:** {stats.total_p0_sps}")
        lines.append(f"- **Dynamically confirmed:** {stats.dynamic_full_verified + stats.dynamic_user_verified} "
                     f"(FirmAE: {stats.dynamic_full_verified}, QEMU: {stats.dynamic_user_verified})")
        lines.append(f"- **Static high confidence:** {stats.static_high_reserved}")
        lines.append(f"- **Discarded:** {stats.discarded}")
        lines.append(f"- **Verification rate:** {stats.verification_rate or 'N/A'}")
        lines.append(f"- **Unique crashes:** {stats.unique_crashes}")
        lines.append("")

        critical_vulns = [v for v in report.vulnerabilities if v.severity == "critical" or v.priority == "P0"]
        if critical_vulns:
            lines.append("### Key Findings")
            lines.append("")
            for v in critical_vulns:
                lines.append(f"- **{v.cwe}** -- {v.title} in `{v.function_name}` "
                           f"(confidence: {v.confidence:.0%}, verification: {v.verification_level})")
        return lines

    def _build_statistics_section(self, stats: Phase4Statistics) -> list:
        lines = ["## Statistics", ""]
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Total P0 SPs | {stats.total_p0_sps} |")
        lines.append(f"| PoCs Generated | {stats.poc_generated} |")
        lines.append(f"| L1 (FirmAE) Confirmed | {stats.dynamic_full_verified} |")
        lines.append(f"| L2 (QEMU) Confirmed | {stats.dynamic_user_verified} |")
        lines.append(f"| L3 (Static High) Reserved | {stats.static_high_reserved} |")
        lines.append(f"| Discarded (False Positive) | {stats.discarded} |")
        lines.append(f"| Unique Crashes | {stats.unique_crashes} |")
        lines.append(f"| Verification Rate | {stats.verification_rate or 'N/A'} |")
        return lines

    def _build_vulnerability_section(self, index: int, v: VulnerabilityEntry) -> list:
        lines = [
            f"### {index}. {v.title}",
            "",
            f"| Field | Detail |",
            f"|-------|--------|",
            f"| **CWE** | {v.cwe} |",
            f"| **SP ID** | `{v.sp_id}` |",
            f"| **Function** | `{v.function_name}` @ `{v.binary_offset or 'N/A'}` |",
            f"| **Severity** | {v.severity} |",
            f"| **Priority** | {v.priority} |",
            f"| **Confidence** | {v.confidence:.0%} |",
            f"| **Verification** | {v.verification_level} |",
            "",
            "#### Description", "", v.description, "",
        ]
        if v.control_flow:
            lines.extend(["#### Control Flow", "", "```", v.control_flow, "```", ""])
        if v.trigger_condition:
            lines.extend(["#### Trigger Condition", "", v.trigger_condition, ""])
        if v.exploitability:
            lines.extend([
                "#### Exploitability Assessment", "",
                f"- **Attack Vector:** {v.exploitability.attack_vector}",
                f"- **Difficulty:** {v.exploitability.difficulty}",
                f"- **Reliability:** {v.exploitability.reliability}",
                f"- **Impact:** {v.exploitability.impact}",
                "",
            ])
        if v.poc:
            lines.extend([
                "#### Proof of Concept", "",
                f"- **Type:** {v.poc.poc_type}",
                f"- **Target:** {v.poc.poc_target.method} "
                f"http://{v.poc.poc_target.host}:{v.poc.poc_target.port}{v.poc.poc_target.path}",
                f"- **Explanation:** {v.poc.poc_explanation}", "",
                "```",
                v.poc.poc_content[:500] + ("\n... (truncated)" if len(v.poc.poc_content) > 500 else ""),
                "```", "",
            ])
        if v.crash_info:
            lines.extend([
                "#### Crash Information", "",
                f"- **Crash Type:** {v.crash_info.crash_type}",
                f"- **Crash Address:** `{v.crash_info.crash_address}`",
                f"- **Signal:** {v.crash_info.signal_number}",
            ])
            if v.crash_info.register_state:
                lines.append(f"- **Registers:** {v.crash_info.register_state}")
            if v.crash_info.backtrace:
                lines.append("- **Backtrace:**")
                for bt in v.crash_info.backtrace[:5]:
                    lines.append(f"  - {bt}")
            lines.append("")
        if v.fix_suggestion:
            lines.extend(["#### Fix Suggestion", "", v.fix_suggestion, ""])
        return lines
